### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LabhanshAgrawal** [hectorqin/hyper-reorderable-tabs#2]
https://github.com/zeit/hyper/pull/3197 is merged but this still doesn't seem to work. I can drag out the tabs but they are not getting reordered.

**Comment by hectorqin** [comment]
Did you build from source?  @LabhanshAgrawal

**Comment by LabhanshAgrawal** [comment]
Yes, from latest canary.

**Comment by hectorqin** [comment]
What's your OS? Is there any error in developer console? I only tested on my Mac 10.14.

**Comment by hectorqin** [comment]
Fixed now.
